apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gis-viewer
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gis-viewer
                port: { number: {{ .Values.service.viewerPort }} }
