apiVersion: v1
kind: Service
metadata: { name: gis-viewer }
spec:
  type: {{ .Values.service.type }}
  selector: { app: gis-viewer }
  ports:
    - port: {{ .Values.service.viewerPort }}
      targetPort: 5173
      name: http
